name: Primer Workflow CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Construir imagen Docker optimizada
        run: docker build -t app-optimizada .

      - name: Medir tamano de imagen optimizada
        run: docker image inspect app-optimizada --format="{{.Size}}"

      - name: Ejecutar contenedor y verificar
        run: |
          docker run -d -p 3000:3000 --name contenedor-optimizado app-optimizada
          sleep 3
          curl http://localhost:3000
          docker stop contenedor-optimizado
