name: Primer Workflow CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '**.js'

jobs:
  saludo:
    runs-on: ubuntu-latest

    env:
      AMBIENTE: "produccion"
      API_KEY: ${{ secrets.API_KEY }}

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Imprimir mensaje
        run: echo "Hola CI/CD"

      - name: Mostrar version de Node.js
        run: node -v

      - name: Mostrar variable de entorno
        run: echo "Ambiente actual $AMBIENTE"

      - name: Verificar secret sin exponerlo
        run: |
          if [ -n "$API_KEY" ]; then
            echo "API_KEY esta configurada correctamente ✓"
          else
            echo "API_KEY no encontrada ✗"
          fi
