name: Primer Workflow CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '**.js'

jobs:
  saludo:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensaje
        run: echo "Hola CI/CD"
